### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by christophnetz** [Inne-Lemstra/Bible_Reader#1]
Hey Prof. Snuggles, may I collaborate?

**Comment by Inne-Lemstra** [comment]
Hi Christoph, 
This bible reader project was kind of a test to play around with R string manipulation.
Maintaining isn't really one off my goals anymore. Becoming a collaborator wouldn't really add a lot of value.
I think it would we better for you to fork it and work with it on your own. This way you can change anything you want. Plus if you make something nice pls send me a pull request. You can also make issues if you do not understand anything.
What do you think??

**Comment by christophnetz** [comment]
Hey Inne, sounds good. Anyway it was more for the purpose of exploring ;)
